- name: delete mariadb
  yum:
    name: mariadb-libs
    state: removed

- name: install rpm
  yum: name={{ item }} state=present
  loop:
    - "{{ MYSQL_VERSION }}"

- name: install mysqld and mysql-devel
  yum: name={{ item }} state=installed
  loop:
    - mysql-community-server
    - mysql-devel

- name: start mysql
  systemd: name=mysqld enabled=yes state=started

- name: get temporary password
  shell: cat /var/log/mysqld.log | grep "temporary password" | awk '{print $11}'
  register: MYSQL_DEFAULT_PASSWORD
  # changed_when: false

- name: update expired root user password
  shell: mysql -u root -p"{{ MYSQL_DEFAULT_PASSWORD.stdout }}" --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ MYSQL_PASSWORD }}';"
  ignore_errors: True
  #changed_when: result.rc != true
