- name: install development tools
  yum: name={{ item }} state=present
  loop:
    - git
    - bzip2
    - gcc
    - openssl-devel
    - readline-devel
    - zlib-devel

- name: git clone rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /usr/local/rbenv/

- name: change .rbenv owner
  file:
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0764
    path: /usr/local/rbenv/

- name: insert/update /etc/profile env
  blockinfile:
    path: /etc/profile
    block: |
      export RBENV_ROOT="/usr/local/rbenv"
      export PATH="${RBENV_ROOT}/bin:${PATH}"
      eval "$(rbenv init -)"

- name: source /etc/profile
  shell: bash -lc "source /etc/profile"

- name: git clone ruby-build
  git:
    repo: git://github.com/sstephenson/ruby-build.git
    dest: /usr/local/rbenv/plugins/ruby-build/

- name: install ruby-build
  shell: bash -lc "/usr/local/rbenv/plugins/ruby-build/install.sh"

- name: install ruby2.5.0
  shell: bash -lc "/usr/local/rbenv/bin/rbenv install -v 2.5.0"

- name: set ruby2.5.0 to gloval
  shell: bash -lc "/usr/local/rbenv/bin/rbenv global 2.5.0"
  ignore_errors: yes
