# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.ssh.username = "menta"
  config.ssh.guest_port = 22
  # config.ssh.private_key_path = "/Users/sumikazuki/Desktop/menta/wordpress/.vagrant/machines/default/virtualbox/private_key"
  # config.ssh.host = "127.0.0.1"
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.10"
end
