# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.10"
  # Virtualboxの共有フォルダでホストOSの「カレントディレクトリ」とゲストOSの「/vagrant」を共有
  config.vm.synced_folder "./", "/home/vagrant", type: "virtualbox"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "install_nginx.yml"
  end
end
